### ISSUE TITLE
UndefVarError: P0 not defined

### ISSUE THREAD

**Issue by lcarmans** [jverzani/SpecialPolynomials.jl#17]
I am trying to fit a curve using Legendre polynomials but I get an error:
UndefVarError: P0 not defined

Indeed in the source code I cannot seem to find a definition for the function P0.

I already found out that the data x should be in Array format and not LinRange.

```
using Polynomials, SpecialPolynomials, Plots


x = LinRange(0,7,30)
y = @.sin(-x)
f = fit(Legendre, Array(x), y)

```

Please let me know if you need further information; this is my first issue post.

**Comment by jverzani** [comment]
Thanks for letting me know! I have this fixed in the branch v0.2.0 that tracks necessary changes to accommodate v2.0.0 of Polynomials. That won't be merged in for awhile, as it has dependencies that will need to make the jump to v2.0.0 of Polynomials which will take some time. Let me look what I need to do to address this smaller change.
